### ISSUE TITLE
build BLUE_BUTTON_F103RET6 error

### ISSUE THREAD

**Issue by skylin008** [PhenixWen/MicroPython_STM32#1]
When make BOARD=BLUE_BUTTON_F103RET6 ,the error information as show:
make BOARD=BLUE_BUTTON_F103RET6
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
CC pin.c
In file included from ../../py/mpstate.h:35:0,
                 from ../../py/runtime.h:29,
                 from pin.c:32:
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:1:55: error: 'GPIO_AF1_TIM1' undeclared here (not in a function)
     { MP_ROM_QSTR(MP_QSTR_AF1_TIM1),       MP_ROM_INT(GPIO_AF1_TIM1) },
                                                       ^
../../py/obj.h:87:67: note: in definition of macro 'MP_OBJ_NEW_SMALL_INT'
 #define MP_OBJ_NEW_SMALL_INT(small_int) ((mp_obj_t)((((mp_uint_t)(small_int)) << 1) | 1))
                                                                   ^~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:1:44: note: in expansion of macro 'MP_ROM_INT'
     { MP_ROM_QSTR(MP_QSTR_AF1_TIM1),       MP_ROM_INT(GPIO_AF1_TIM1) },
                                            ^~~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:2:55: error: 'GPIO_AF1_TIM2' undeclared here (not in a function)
     { MP_ROM_QSTR(MP_QSTR_AF1_TIM2),       MP_ROM_INT(GPIO_AF1_TIM2) },
                                                       ^
../../py/obj.h:87:67: note: in definition of macro 'MP_OBJ_NEW_SMALL_INT'
 #define MP_OBJ_NEW_SMALL_INT(small_int) ((mp_obj_t)((((mp_uint_t)(small_int)) << 1) | 1))
                                                                   ^~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:2:44: note: in expansion of macro 'MP_ROM_INT'
     { MP_ROM_QSTR(MP_QSTR_AF1_TIM2),       MP_ROM_INT(GPIO_AF1_TIM2) },
                                            ^~~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:3:55: error: 'GPIO_AF2_TIM3' undeclared here (not in a function)
     { MP_ROM_QSTR(MP_QSTR_AF2_TIM3),       MP_ROM_INT(GPIO_AF2_TIM3) },
                                                       ^
../../py/obj.h:87:67: note: in definition of macro 'MP_OBJ_NEW_SMALL_INT'
 #define MP_OBJ_NEW_SMALL_INT(small_int) ((mp_obj_t)((((mp_uint_t)(small_int)) << 1) | 1))
                                                                   ^~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:3:44: note: in expansion of macro 'MP_ROM_INT'
     { MP_ROM_QSTR(MP_QSTR_AF2_TIM3),       MP_ROM_INT(GPIO_AF2_TIM3) },
                                            ^~~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:5:55: error: 'GPIO_AF3_I2C1' undeclared here (not in a function)
     { MP_ROM_QSTR(MP_QSTR_AF3_I2C1),       MP_ROM_INT(GPIO_AF3_I2C1) },
                                                       ^
../../py/obj.h:87:67: note: in definition of macro 'MP_OBJ_NEW_SMALL_INT'
 #define MP_OBJ_NEW_SMALL_INT(small_int) ((mp_obj_t)((((mp_uint_t)(small_int)) << 1) | 1))
                                                                   ^~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:5:44: note: in expansion of macro 'MP_ROM_INT'
     { MP_ROM_QSTR(MP_QSTR_AF3_I2C1),       MP_ROM_INT(GPIO_AF3_I2C1) },
                                            ^~~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:8:55: error: 'GPIO_AF4_SPI1' undeclared here (not in a function)
     { MP_ROM_QSTR(MP_QSTR_AF4_SPI1),       MP_ROM_INT(GPIO_AF4_SPI1) },
                                                       ^
../../py/obj.h:87:67: note: in definition of macro 'MP_OBJ_NEW_SMALL_INT'
 #define MP_OBJ_NEW_SMALL_INT(small_int) ((mp_obj_t)((((mp_uint_t)(small_int)) << 1) | 1))
                                                                   ^~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:8:44: note: in expansion of macro 'MP_ROM_INT'
     { MP_ROM_QSTR(MP_QSTR_AF4_SPI1),       MP_ROM_INT(GPIO_AF4_SPI1) },
                                            ^~~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:11:55: error: 'GPIO_AF5_USART1' undeclared here (not in a function)
     { MP_ROM_QSTR(MP_QSTR_AF5_USART1),     MP_ROM_INT(GPIO_AF5_USART1) },
                                                       ^
../../py/obj.h:87:67: note: in definition of macro 'MP_OBJ_NEW_SMALL_INT'
 #define MP_OBJ_NEW_SMALL_INT(small_int) ((mp_obj_t)((((mp_uint_t)(small_int)) << 1) | 1))
                                                                   ^~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:11:44: note: in expansion of macro 'MP_ROM_INT'
     { MP_ROM_QSTR(MP_QSTR_AF5_USART1),     MP_ROM_INT(GPIO_AF5_USART1) },
                                            ^~~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:14:55: error: 'GPIO_AF5_USART2' undeclared here (not in a function)
     { MP_ROM_QSTR(MP_QSTR_AF5_USART2),     MP_ROM_INT(GPIO_AF5_USART2) },
                                                       ^
../../py/obj.h:87:67: note: in definition of macro 'MP_OBJ_NEW_SMALL_INT'
 #define MP_OBJ_NEW_SMALL_INT(small_int) ((mp_obj_t)((((mp_uint_t)(small_int)) << 1) | 1))
                                                                   ^~~~~~~~~
build-BLUE_BUTTON_F103RET6/genhdr/pins_af_const.h:14:44: note: in expansion of macro 'MP_ROM_INT'
     { MP_ROM_QSTR(MP_QSTR_AF5_USART2),     MP_ROM_INT(GPIO_AF5_USART2) },
                                            ^~~~~~~~~~
../../py/mkrules.mk:47: recipe for target 'build-BLUE_BUTTON_F103RET6/pin.o' failed
make: *** [build-BLUE_BUTTON_F103RET6/pin.o] Error 1

How to solve this issue.Thanks!

**Comment by PhenixWen** [comment]
You can see make-pins.py  just works for STM32F4xx, still need to modify it for STM32F103 serials.

**Comment by PhenixWen** [comment]
It is OK now for BLUE_BUTTON_F103RET6.  But some functions need to fill when debug it.
==========================================================
arm-none-eabi-size build-BLUE_BUTTON_F103RET6/firmware.elf
   text    data     bss     dec     hex filename
 284200      28   27464  311692   4c18c build-BLUE_BUTTON_F103RET6/firmware.elf
Create build-BLUE_BUTTON_F103RET6/firmware.dfu
arm-none-eabi-objcopy -O binary -j .isr_vector build-BLUE_BUTTON_F103RET6/firmware.elf build-BLUE_BUTTON_F103RET6/firmware0.bin
arm-none-eabi-objcopy -O binary -j .text -j .data build-BLUE_BUTTON_F103RET6/firmware.elf build-BLUE_BUTTON_F103RET6/firmware1.bin
python ../../tools/dfu.py -b 0x08000000:build-BLUE_BUTTON_F103RET6/firmware0.bin -b 0x08020000:build-BLUE_BUTTON_F103RET6/firmware1.bin build-BLUE_BUTTON_F103RET6/firmware.dfu
Create build-BLUE_BUTTON_F103RET6/firmware.hex
arm-none-eabi-objcopy -O ihex build-BLUE_BUTTON_F103RET6/firmware.elf build-BLUE_BUTTON_F103RET6/firmware.hex
